### ISSUE TITLE
Geary failing in CI; possibly due to libpysal#510 

### ISSUE THREAD

**Issue by jGaboardi** [pysal/esda#239] opened 2023-01-18 00:37 UTC
The `DEV` versions ([`310-DEV`](https://github.com/pysal/esda/actions/runs/3943699264/jobs/6748833959#step:7:245) and [`310-numba-DEV`](https://github.com/pysal/esda/actions/runs/3943699264/jobs/6748834081#step:7:245)), Seems to be due to https://github.com/pysal/libpysal/pull/510.

**Comment by sjsrey** [comment] 2023-02-11 18:26
Two more failures to debug:

- [esda/tests/test_silhouette.py](https://github.com/pysal/esda/actions/runs/3943699264/jobs/7183652625#step:7:367)
- [join_counts](https://github.com/pysal/esda/actions/runs/3943699264/jobs/7183652625#step:7:82)

**Comment by sjsrey** [comment] 2023-02-13 20:57
Locally, I'm unable to reproduce these failures:

```
(test) ☁  esda [dev-310-esda] uname -a
Linux pop-os 6.0.12-76060006-generic 

In [1]: import shapely

In [2]: shapely.__version__
Out[2]: '2.0.1'

In [3]: import geopandas as gpd

In [4]: gpd.__version__
Out[4]: '0.12.2'


```

**Comment by jGaboardi** [comment] 2023-02-13 21:36
@sjsrey Which version of `libpysal` are you running?

**Comment by sjsrey** [comment] 2023-02-13 21:38
In [6]: import libpysal

In [7]: libpysal.__version__
Out[7]: '4.7.0'

**Comment by sjsrey** [comment] 2023-02-13 22:16
The failure for `test_Join_Counts` is using a constructed `W` from `lat2W`, there are no geometries involved in this test.
https://github.com/pysal/esda/blob/b0f7aa5daa6570be54f7da2c562aee6043e7b7b9/esda/tests/test_join_counts.py#L14-L45

And, the failure (line 31)  is after the comparisons of the join counts, which all pass. I would expect those to fail if the indexing of the W was off. 

No answer yet, just more information.

**Comment by martinfleis** [comment] 2023-08-03 10:49
don't see these failures anymore. Can this be closed?

**Comment by sjsrey** [comment] 2023-08-03 14:10
Thanks for checking on this. Closing.

**Closed by sjsrey** 2023-08-03 14:11 UTC
Labels: ci
