### ISSUE TITLE
Cannot assign slice from input of different size - error in SpaceGAN code

### ISSUE THREAD

**Issue by Pranav110500** [pysal/esda#214] opened 2022-07-29 10:12 UTC
So I am trying to implement a SpaceGAN model, (obtained from https://github.com/konstantinklemmer/spacegan), on a small dataset of 11 points (given below in csv format along with the colab file). Can someone explain to me why the aforementioned error is popping up and how to rectify it to help this model work?

Colab file:-
https://colab.research.google.com/drive/1hsK1MNx4kgbO7lB3ktITnYRNG9YOZQrk?usp=sharing

CSV File:-
[SoilValuesLatLong.csv](https://github.com/pysal/esda/files/9218968/SoilValuesLatLong.csv)

**Comment by knaaptime** [comment] 2022-07-29 15:12
sounds like a duplicate of #171, which happens when some of your observations have no neighbors. Try tweaking your weights matrix or install the current dev version from github. A fix is provided in #190 and will be released shortly

**Comment by jGaboardi** [comment] 2022-11-23 18:36
Fixed in #190.

**Closed by jGaboardi** 2022-11-23 18:36 UTC
