### ISSUE TITLE
How to calculate local moran I in island points?

### ISSUE THREAD

**Issue by GIS-PanTianLi** [pysal/esda#204] opened 2022-03-07 06:51 UTC
I have got a large amount of house price point data from Internet and I noticed that there are some outliers in the dataset. Currently I am trying to use local moran I to detect them, and it works in ArcGIS, so I have want to try it in PySAL. However, by using esda.moran.Moran_Local(house_price, weightMatrix) using inverse distance weight, and I got below errors. Turns out this method fails in island point, and I wonder is there any solution to this situation?

My brief code is as below:
    year_data = point_data[point_data['deal_year'] == year]
    year_data = year_data.to_crs('EPSG:32649')
    coord_list = [(x,y) for x,y in zip(year_data['geometry'].x , year_data['geometry'].y)]
    house_price = year_data['total_pric']
    weightMatrix = libpysal.weights.DistanceBand(np.array(coord_list),threshold=3000,binary=False)
    # weightMatrix.transform = 'U'
    esda.moran.Moran_Local(house_price, weightMatrix)

Here are my errors

D:\Anaconda3\envs\testProj\lib\site-packages\libpysal\weights\weights.py:172: UserWarning: The weights matrix is not fully connected: 
 There are 49 disconnected components.
 There are 33 islands with ids: 46, 47, 57, 72, 83, 84, 85, 94, 104, 105, 119, 120, 121, 136, 137, 306, 308, 2137, 2183, 3011, 3076, 3396, 3601, 3998, 4215, 4414, 4971, 5158, 5356, 5443, 5487, 5888, 6009.
  warnings.warn(message)

Traceback (most recent call last):
  File "D:\pycharm\PyCharm 2020.1.5\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\pycharm\PyCharm 2020.1.5\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Land_subsidence/to_hpc3/process_gzHP.py", line 144, in <module>
    li = esda.moran.Moran_Local(house_price, weightMatrix)
  File "D:\Anaconda3\envs\testProj\lib\site-packages\esda\moran.py", line 1032, in __init__
    self.p_sim, self.rlisas = _crand_plus(
  File "D:\Anaconda3\envs\testProj\lib\site-packages\esda\crand.py", line 179, in crand
    larger, rlocals = compute_chunk(
  File "D:\Anaconda3\envs\testProj\lib\site-packages\esda\crand.py", line 297, in compute_chunk
    rstats = stat_func(chunk_start + i, z, permuted_ids, weights_i, scaling)
  File "D:\Anaconda3\envs\testProj\lib\site-packages\esda\moran.py", line 1796, in _moran_local_crand
    zi, zrand = _prepare_univariate(i, z, permuted_ids, other_weights)
  File "D:\Anaconda3\envs\testProj\lib\site-packages\esda\crand.py", line 532, in _prepare_univariate
    zrand = z_no_i[flat_permutation_ids].reshape(-1, cardinality)
ValueError: cannot reshape array of size 0 into shape (0)

Please help me if you are available.  Thanks!

**Comment by knaaptime** [comment] 2022-07-27 17:15
duplicate of #167

**Closed by knaaptime** 2022-07-27 17:15 UTC
